In [1]:
import pandas as pd

In [2]:
url = "data/nhanes_2015_2016.csv"
da = pd.read_csv(url)

In [3]:
da

SEQN  ALQ101  ALQ110  ALQ130  SMQ020  RIAGENDR  RIDAGEYR  RIDRETH1  \
0     83732     1.0     NaN     1.0       1         1        62         3   
1     83733     1.0     NaN     6.0       1         1        53         3   
2     83734     1.0     NaN     NaN       1         1        78         3   
3     83735     2.0     1.0     1.0       2         2        56         3   
4     83736     2.0     1.0     1.0       2         2        42         4   
...     ...     ...     ...     ...     ...       ...       ...       ...   
5730  93695     2.0     2.0     NaN       1         2        76         3   
5731  93696     2.0     2.0     NaN       2         1        26         3   
5732  93697     1.0     NaN     1.0       1         2        80         3   
5733  93700     NaN     NaN     NaN       1         1        35         3   
5734  93702     1.0     NaN     2.0       2         2        24         3   

      DMDCITZN  DMDEDUC2  ...  BPXSY2  BPXDI2  BMXWT  BMXHT  BMXBMI  BMXLEG  \
0          1.0       5.0  ...   124.0    64.0   94.8  184.5    27.8    43.3   
1          2.0       3.0  ...   140.0    88.0   90.4  171.4    30.8    38.0   
2          1.0       3.0  ...   132.0    44.0   83.4  170.1    28.8    35.6   
3          1.0       5.0  ...   134.0    68.0  109.8  160.9    42.4    38.5   
4          1.0       4.0  ...   114.0    54.0   55.2  164.9    20.3    37.4   
...        ...       ...  ...     ...     ...    ...    ...     ...     ...   
5730       1.0       3.0  ...   112.0    46.0   59.1  165.8    21.5    38.2   
5731       1.0       5.0  ...   116.0    76.0  112.1  182.2    33.8    43.4   
5732       1.0       4.0  ...   146.0    58.0   71.7  152.2    31.0    31.3   
5733       2.0       1.0  ...   106.0    66.0   78.2  173.3    26.0    40.3   
5734       1.0       5.0  ...   114.0    68.0   58.3  165.0    21.4    38.2   

      BMXARML  BMXARMC  BMXWAIST  HIQ210  
0        43.6     35.9     101.1     2.0  
1        40.0     33.2     107.9     NaN  
2        37.0     31.0     116.5     2.0  
3        37.7     38.3     110.1     2.0  
4        36.0     27.2      80.4     2.0  
...       ...      ...       ...     ...  
5730     37.0     29.5      95.0     2.0  
5731     41.8     42.3     110.2     2.0  
5732     37.5     28.8       NaN     2.0  
5733     37.5     30.6      98.9     2.0  
5734     33.5     26.2      72.5     2.0  

[5735 rows x 28 columns]

In [4]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='object')

In [5]:
da["BMXWT"]            # we can get a mean

0        94.8
1        90.4
2        83.4
3       109.8
4        55.2
        ...  
5730     59.1
5731    112.1
5732     71.7
5733     78.2
5734     58.3
Name: BMXWT, Length: 5735, dtype: float64

In [8]:
da["BMXWT"].mean()

np.float64(81.34267560889516)

In [10]:
# Demagraphics on education: cdc.gov/nchs/nhanes/2015-2016/SMQ_I.htm  (this link now does not work)

In [23]:
da['DMDEDUC2'].unique()         # categorical ordered

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [22]:
g = da['RIAGENDR']       # categorical unordered

In [20]:
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [21]:
g.unique()

array([1, 2])

In [24]:
# One Hot Encoding 

In [29]:
B = ['bird', 'cat', 'dog', 'cat', 'bird', 'bird']
d = {"categorical": B}
df = pd.DataFrame(d)

In [28]:
df

catagorical
0        bird
1         cat
2         dog
3         cat
4        bird
5        bird

In [30]:
df["categorical"]

0    bird
1     cat
2     dog
3     cat
4    bird
5    bird
Name: categorical, dtype: object

In [47]:
# "dummies" is used to create colomns corresponding to unique values
dfDummies = pd.get_dummies(df["categorical"], prefix = "category", dtype=int)     # see what happen when remove dtype parameter

In [48]:
dfDummies

category_bird  category_cat  category_dog
0              1             0             0
1              0             1             0
2              0             0             1
3              0             1             0
4              1             0             0
5              1             0             0

In [49]:
dfDummies.values

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])